### ISSUE TITLE
RavenDB v4 support

### ISSUE THREAD

**Issue by AKlaus** [mj1856/RavenDB-NodaTime#18]
Hi Matt, thanks for the projects, it works like a charm!

Just one thing, _RavenDB v4_ has been out since February and they changed the interfaces, so _RavenDB-NodaTime_ can't be configured anymore.

Would it be possible to release a new version of _RavenDB-NodaTime_ to support RavenDB v4?

**Comment by ryanheath** [comment]
Hi Alex,

I’ll look into this weekend, let’s what we can do.

What do you mean with: ‘they changed the interfaces, so
*RavenDB-NodaTime* can't
be configured anymore‘

It could help if you can pinpoint what has changed.

Thanks!

// Ryan

**Comment by ryanheath** [comment]
@AKlaus Just to let you know I am working on it. 
Most tests are succeeding, but quite a few are failing, mostly about using NodaTime in indexes or server side.

**Comment by AKlaus** [comment]
@ryanheath, would you mind creating a branch with your changes here on GitHub, so I could be of any help?

**Comment by ryanheath** [comment]
Yes, I will. But first we need to bring (back) some functionality into ravendb 4.
Our lib is depending on it, but it was removed from ravendb 4. I hope to do/start with it this week.

**Comment by ryanheath** [comment]
https://github.com/ravendb/ravendb/pull/6415 is merged!
Now we can proceed further.

**Comment by AKlaus** [comment]
Great news! It seems to be a massive work!
I see that [RavenDB pull requests](http://issues.hibernatingrhinos.com/issue/RavenDB-11361) been merged into master and should be available in the nightly build. 
Does it mean that if I use the nightly build and the code from [feature/upgrade-v40 branch](https://github.com/mj1856/RavenDB-NodaTime/tree/feature/upgrade-v40) it should all be working?

**Comment by ryanheath** [comment]
If you only use the clientside of the lib then you can do that, yes.
Serverside of the lib has still some issues.

**Comment by AKlaus** [comment]
I can confirm that the client-side is working great with RavenDb v4.0.5

**Comment by ryanheath** [comment]
Great to here!

I want to wait for v4.0.6 to release a NuGet package.

// Ryan

**Comment by tobiaszuercher** [comment]
i did a fork of your raven4-update branch and added a sample console exe (https://github.com/tobiaszuercher/RavenDB-NodaTime/blob/feature/upgrade-v40/src/Sample/Program.cs).

using `RavenDB Server 4.0.6-patch-40047` (as mentioned in ravendb maillist https://groups.google.com/forum/#!topic/ravendb/5CpsLbz2epY)  and copying `NodaTime.dll`, `Raven.Bundles.NodaTime.dll` to the server.exe i get the following index errors:

```Failed to execute mapping function on people/33-A. Exception: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: The best overloaded method match for 'Raven.Bundles.NodaTime.NodaTimeField.AsInstant(System.DateTime)' has some invalid arguments
   at CallSite.Target(Closure , CallSite , Type , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Raven.Server.Documents.Indexes.Static.Generated.Index_ServerSideNodaTime_Index.<>c.<.ctor>b__0_2(Object this0)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Raven.Server.Documents.Indexes.Static.TimeCountingEnumerable.Enumerator.MoveNext() in C:\Builds\RavenDB-4.0-Patch\src\Raven.Server\Documents\Indexes\Static\TimeCountingEnumerable.cs:line 41
   at Raven.Server.Documents.Indexes.MapIndexBase`2.HandleMap(LazyStringValue lowerId, IEnumerable mapResults, IndexWriteOperation writer, TransactionOperationContext indexContext, IndexingStatsScope stats) in C:\Builds\RavenDB-4.0-Patch\src\Raven.Server\Documents\Indexes\MapIndexBase.cs:line 64
   at Raven.Server.Documents.Indexes.Workers.MapDocuments.Execute(DocumentsOperationContext databaseContext, TransactionOperationContext indexContext, Lazy`1 writeOperation, IndexingStatsScope stats, CancellationToken token) in C:\Builds\RavenDB-4.0-Patch\src\Raven.Server\Documents\Indexes\Workers\MapDocuments.cs:line 108```

Repro: https://github.com/tobiaszuercher/RavenDB-NodaTime/blob/feature/upgrade-v40/src/Sample/Program.cs

I don't understand how Raven.Bundles.NodaTime.NodaTimeField.AsInstant gets registered to the Server.

**Comment by ryanheath** [comment]
I have cloned your project but it seems to work ok.

I had to restart the ravendb server though, otherwise it will not pickup the added dlls.

HTH
// Ryan

**Comment by tobiaszuercher** [comment]
hi @ryanheath,
thank you for checking my sample out!

> I had to restart the ravendb server though
i didn't forget that.

> I have cloned your project but it seems to work ok.
the c# code goes through without issues. the studio tells me about the errors:

![Image of Yaktocat](http://codevision.ch/indexerror1.jpg)
![Image of Yaktocat](http://codevision.ch/indexerror2.jpg)

does your index work?

**Comment by tobiaszuercher** [comment]
i could get it running now! i did wipe all the docs and restart from scratch. i dont understand why, but it works now!

thank you!

**Comment by ryanheath** [comment]
Glad it worked out for you! :)

// Ryan

**Comment by markzielinski** [comment]
Hi, great work on this.  Has there been a NuGet package released with support for RavenDB 4.x yet?

**Comment by ryanheath** [comment]
No, I’m waiting for 4.0.6 to come out officially.
I don’t want to make a release on a patched version.
It could be anytime now ...

// Ryan

**Comment by markzielinski** [comment]
Thanks for the update.   I actually just went ahead and built my own quick extension to serialize Instant types which was quicker for me than waiting it out for the package.

**Comment by ryanheath** [comment]
Yes, that is possible but there are some corner case which do not work out of the box.
Hopefully they will release a 'good' version any time soon ...

// Ryan

**Comment by ryanheath** [comment]
Release v4.0.0 fe48505462342ba05273607292f740d0c8ec204f
